#!/bin/bash
# =============================================================================
# DREAMING-LOCAL - Local Session Pattern Analysis (Ollama only)
#
# Lightweight version of dreaming.sh that runs entirely on local LLM.
# Analyzes session logs from the last 7 days, extracts recurring errors,
# success patterns, and workflow improvements.
#
# Cron: 0 5 * * 0 (Sunday 05:00, after main dreaming)
# Safeguards:
# - Read-only on sessions, writes only to playbooks directory
# - No PII in reports (session IDs are truncated)
# - Max 240s Ollama timeout per analysis
# - Bypass: touch /tmp/autonomie/dreaming-local-skip
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../config.sh
source "$SCRIPT_DIR/../../config.sh"

LOG="$LOG_DIR/dreaming-local.log"
PLAYBOOK_DIR="$VAULT_DIR/playbooks"
REPORT_FILE="$PLAYBOOK_DIR/dreaming-report-$(date +%Y-%m-%d).md"
PLAYBOOK_FILE="$PLAYBOOK_DIR/auto-playbooks.md"
TODAY=$(date +%Y-%m-%d)
WEEK_AGO=$(date -d '7 days ago' +%Y-%m-%d 2>/dev/null || date -v-7d +%Y-%m-%d)

log() { echo "$(date -Iseconds) $1" >> "$LOG" 2>/dev/null; }

# Guards
SKIP_FILE="$LOCKFILE_DIR/dreaming-local-skip"
if [ -f "$SKIP_FILE" ]; then
  rm -f "$SKIP_FILE"
  log "bypass"
  exit 0
fi

if ! curl -s --max-time 5 "$OLLAMA_URL/api/tags" > /dev/null 2>&1; then
  log "ERROR: Ollama not reachable at $OLLAMA_URL"
  exit 1
fi

log "start"

# Collect session files from last 7 days
CURRENT_MONTH=$(date +%Y-%m)
LAST_MONTH=$(date -d '7 days ago' +%Y-%m 2>/dev/null || date -v-7d +%Y-%m)

SESSION_FILES=""
for month_dir in "$SESSIONS_DIR/$CURRENT_MONTH" "$SESSIONS_DIR/$LAST_MONTH"; do
  [ -d "$month_dir" ] || continue
  while IFS= read -r f; do
    fname=$(basename "$f")
    fdate="${fname:0:10}"
    if [[ "$fdate" > "$WEEK_AGO" || "$fdate" == "$WEEK_AGO" ]]; then
      SESSION_FILES="$SESSION_FILES $f"
    fi
  done < <(find "$month_dir" -name "*.md" -type f 2>/dev/null)
done

# Also check loose files directly under sessions dir
while IFS= read -r f; do
  fname=$(basename "$f")
  fdate="${fname:0:10}"
  if [[ "$fdate" > "$WEEK_AGO" || "$fdate" == "$WEEK_AGO" ]]; then
    SESSION_FILES="$SESSION_FILES $f"
  fi
done < <(find "$SESSIONS_DIR" -maxdepth 1 -name "*.md" -type f 2>/dev/null)

FILE_COUNT=$(echo $SESSION_FILES | wc -w)
if [ "$FILE_COUNT" -lt 1 ]; then
  log "no sessions found"
  exit 0
fi

log "analyzing $FILE_COUNT sessions"

# Collect session contents (max 50 lines per file, max 8 files)
COMBINED=""
COUNT=0
for f in $SESSION_FILES; do
  [ $COUNT -ge 8 ] && break
  CONTENT=$(head -50 "$f" 2>/dev/null || true)
  COMBINED="$COMBINED

--- SESSION: $(basename "$f") ---
$CONTENT"
  COUNT=$((COUNT + 1))
done

# Local LLM analysis
PROMPT="Analyze these session logs from an AI agent system. Find:

1. RECURRING ERRORS: Which problems appear multiple times?
2. SUCCESS PATTERNS: What worked particularly well?
3. WORKFLOW IMPROVEMENTS: Which processes could be optimized?
4. NEW PLAYBOOKS: Are there solutions that should be documented as playbooks?

Answer concisely in Markdown. Max 50 lines. No PII (no names, emails, phone numbers).
Focus on ACTIONABLE insights.

Sessions:
$COMBINED"

PROMPT_JSON=$(printf '%s' "$PROMPT" | jq -Rs .)

RESPONSE=$(curl -s --max-time 240 "$OLLAMA_URL/api/generate" \
  -d "{\"model\":\"$OLLAMA_MODEL\",\"prompt\":$PROMPT_JSON,\"stream\":false,\"options\":{\"num_predict\":2048,\"temperature\":0.3}}" \
  2>/dev/null | jq -r '.response // "ERROR: No response"' 2>/dev/null)

if [ -z "$RESPONSE" ] || [ "$RESPONSE" = "ERROR: No response" ]; then
  log "ERROR: Ollama analysis failed"
  exit 1
fi

# Write report
mkdir -p "$PLAYBOOK_DIR" 2>/dev/null
cat > "$REPORT_FILE" << EOF
# Dreaming Report - $TODAY

> Automatically generated by dreaming-local.sh
> Analyzed sessions: $FILE_COUNT (last 7 days)
> Model: $OLLAMA_MODEL

$RESPONSE

---
*Generated: $(date -Iseconds)*
EOF

# Update playbook file (append, do not overwrite)
if [ ! -f "$PLAYBOOK_FILE" ]; then
  cat > "$PLAYBOOK_FILE" << 'HEADER'
# Auto-Playbooks

> Automatically extracted by Dreaming-Local.
> Review manually and convert to skills where appropriate.

HEADER
fi

echo "" >> "$PLAYBOOK_FILE"
echo "## $TODAY" >> "$PLAYBOOK_FILE"
echo "" >> "$PLAYBOOK_FILE"
echo "$RESPONSE" | grep -E '^\d\.|^-|^##' >> "$PLAYBOOK_FILE" 2>/dev/null || true

log "done: $REPORT_FILE ($FILE_COUNT sessions analyzed)"
echo "Dreaming Report written: $REPORT_FILE"
