#!/bin/bash
# =============================================================================
# LEARNING-APPLY - Converts best learning items into concrete actions
#
# Strategy:
# 1. Fetch top-50 items (high-recurrent + unread)
# 2. LLM classifies: guard|memory|vault|skip
# 3. "skip" items are marked as applied (noise)
# 4. Actionable items are written as proposals to vault
# 5. Bulk archival: items with occurrence_count=1 older than 14 days
#
# Cron: 0 6 * * 0  (Sundays 06:00)
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../config.sh
source "$SCRIPT_DIR/../../config.sh"

LOG="$LOG_DIR/learning-apply.log"
TODAY=$(date +%Y-%m-%d)
ACTIONS_DIR="$VAULT_DIR/autonomie/learning-actions"

mkdir -p "$ACTIONS_DIR" "$(dirname "$LOG")" 2>/dev/null

log() { autonomie_log "learning-apply" "$*"; }

log "====== Learning Apply Start ======"

# Phase 1: Bulk archival of noise
ARCHIVED_1=$(autonomie_db "
  UPDATE learning_items SET applied = true, applied_at = NOW()
  WHERE applied = false
    AND occurrence_count = 1
    AND created_at < NOW() - INTERVAL '14 days'
  RETURNING id;" | wc -l)
ARCHIVED_2=$(autonomie_db "
  UPDATE learning_items SET applied = true, applied_at = NOW()
  WHERE applied = false
    AND occurrence_count <= 2
    AND created_at < NOW() - INTERVAL '30 days'
  RETURNING id;" | wc -l)
ARCHIVED=$((ARCHIVED_1 + ARCHIVED_2))
log "Phase 1: $ARCHIVED items archived ($ARCHIVED_1 single-occurrence >14d, $ARCHIVED_2 double-occurrence >30d)"

# Phase 2: Fetch top-50 actionable items
TOP_ITEMS=$(autonomie_db "
  SELECT id || '|' || source || '|' || LEFT(lesson, 200) || '|' || occurrence_count
  FROM learning_items
  WHERE applied = false
  ORDER BY occurrence_count DESC, created_at DESC
  LIMIT 50;")

REMAINING=$(autonomie_db "SELECT COUNT(*) FROM learning_items WHERE applied = false;")
log "Phase 2: $REMAINING items remaining, top 50 fetched"

if [ -z "$TOP_ITEMS" ]; then
  log "No open items. Done."
  exit 0
fi

# Phase 3: LLM classification
if [ -z "$ANTHROPIC_API_KEY" ]; then
  log "No API key, skipping classification"
  log "====== Learning Apply Complete (archival only) ======"
  exit 0
fi

CLASSIFY_PROMPT="You are a DevOps analyst. Classify these learning items from an AI agent system.

For each item: Decide whether it needs a CONCRETE action or is noise.

Format per line (EXACTLY like this, pipe-separated):
ID|ACTION|DESCRIPTION

ACTION is one of:
- guard: New guard or guard change needed
- memory: New memory file or memory update needed
- vault: New vault entry needed
- config: Settings or cron change needed
- skip: Noise, already implemented, or too vague for an action

Rules:
- At least 30% should be 'skip' (not everything is actionable)
- For 'skip': DESCRIPTION = short reason (e.g. 'too vague', 'already implemented', 'one-time problem')
- For actions: DESCRIPTION = concrete next step
- No markdown, no prose

Items (id|source|lesson|occurrence_count):
$TOP_ITEMS"

CLASSIFICATIONS=$(autonomie_llm "$CLASSIFY_PROMPT" 16384 0.3) || CLASSIFICATIONS=""

if [ -z "$(printf '%s' "$CLASSIFICATIONS" | tr -d '[:space:]')" ]; then
  log "ERROR: No classification received"
  exit 1
fi

log "Phase 3: Classification received"

# Phase 4: Process results
SKIPPED=0
ACTIONED=0
ACTION_REPORT=""

while IFS='|' read -r item_id action description; do
  item_id=$(echo "$item_id" | tr -cd '0-9')
  [ -z "$item_id" ] && continue
  action=$(echo "$action" | tr -d ' ' | tr '[:upper:]' '[:lower:]')

  case "$action" in
    skip)
      autonomie_db "UPDATE learning_items SET applied = true, applied_at = NOW() WHERE id = $item_id AND applied = false;" > /dev/null
      SKIPPED=$((SKIPPED + 1))
      ;;
    guard|memory|vault|config)
      ACTION_REPORT="${ACTION_REPORT}
- **[$action]** Item #$item_id: $description"
      ACTIONED=$((ACTIONED + 1))
      ;;
  esac
done <<< "$CLASSIFICATIONS"

log "Phase 4: $SKIPPED items archived as noise, $ACTIONED actions identified"

# Phase 5: Write action report to vault
if [ $ACTIONED -gt 0 ]; then
  REPORT_FILE="$ACTIONS_DIR/actions-$TODAY.md"
  cat > "$REPORT_FILE" << EOF
---
title: Learning Actions $TODAY
type: learning-actions
date: $TODAY
items_archived: $((ARCHIVED + SKIPPED))
actions: $ACTIONED
items_remaining: $REMAINING
---

# Learning Actions - $TODAY

## Summary
- $ARCHIVED noise items archived (age-based)
- $SKIPPED items classified as noise
- $ACTIONED concrete actions identified
- $REMAINING items remaining

## Actions
$ACTION_REPORT

---
*Generated by learning-apply.sh*
EOF
  log "Report written: $REPORT_FILE"
fi

FINAL_COUNT=$(autonomie_db "SELECT COUNT(*) FROM learning_items WHERE applied = false;")
log "====== Learning Apply Complete: $FINAL_COUNT items remaining ======"
